SELECT P.PRODUCT_CODE, SUM(P.PRICE * O.SALES_AMOUNT) SALES #상품코드, 상품코드 별 매출액 합계
FROM PRODUCT P JOIN OFFLINE_SALE O
ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY P.PRODUCT_CODE #상품코드로 그룹핑
ORDER BY SALES DESC, P.PRODUCT_CODE